export const SET_LOADING = 'SET_LOADING';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_REPOS = 'SEARCH_REPOS';
export const SET_SEARCH_USERS_TOTAL = 'SET_SEARCH_USERS_TOTAL';
export const SET_SEARCH_REPOS_TOTAL = 'SET_SEARCH_REPOS_TOTAL';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
